spring:
  application:
    name: SpringBatchPoc

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root

#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: false

logging:
  level:
    com.chrendon: DEBUG

config:
  sftp-connection:
    host: localhost
    port: 2222
    user: sftpuser
    private-key:  "id_rsa"
    pass-phrase: ""
    remote-path: /upload
  csv-processor:
    chunk-size: 5
    reader:
      uri: file:F:\Proyectos\Contactabilidad\SpringBatchPoc\sftp_files\cat_bloqueo_tel_email_lista_negra.csv
      path: cat_bloqueo_tel_email_lista_negra.csv
      line-delimiter: "|"
      column-names: entityCode,blackListType,blackListValue,lastModified,lastUpdated
      skip-lines: 1
